import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es'); // 'es' para español, 'en' para inglés

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  };

  const translations = {
    es: {
      names: 'Fer & Sean',
      date: '18 abril 2026',
      venue: '"La Cueva de la Luna"',
      location: 'Tequila Jalisco, México',
      days: 'Días',
      hours: 'Horas',
      minutes: 'Min',
      seconds: 'Seg',
      comingSoonNote: 'Próximamente se presentará el sitio web con toda la información relacionada',
      languageButton: 'EN',
      // Header translations
      home: 'Inicio',
      about: 'Acerca de',
      portfolio: 'Galería',
      contact: 'Contacto',
      story: 'Nuestra Historia',
      accommodation: 'Alojamiento',
      rsvp: 'RSVP',
      gallery: 'Galería',
      planners: 'Planners',
      service: 'Servicio',
      pricing: 'Precios',
      authPages: 'Páginas de Auth',
      login: 'Iniciar Sesión',
      register: 'Registrarse',
      forgotPassword: 'Olvidé Contraseña',
      comingSoon: 'Próximamente',
      error404: 'Error 404',
      portfolioGrid: 'Portafolio Grid',
      portfolioMasonary: 'Portafolio Masonary',
      portfolioMasonaryS2: 'Portafolio Masonary S2',
      portfolioMasonaryS3: 'Portafolio Masonary S3',
      portfolioSingle: 'Portafolio Single',
      ourStory: 'Nuestra Historia',
      ourStoryStyle1: 'Nuestra Historia Estilo 1',
      ourStoryStyle2: 'Nuestra Historia Estilo 2',
      ourStoryStyle3: 'Nuestra Historia Estilo 3',
      ourStoryStyle4: 'Nuestra Historia Estilo 4',
      ourStoryStyle5: 'Nuestra Historia Estilo 5',
      ourStoryStyle6: 'Nuestra Historia Estilo 6',
      rsvpStyle1: 'RSVP Estilo 1',
      rsvpStyle2: 'RSVP Estilo 2',
      rsvpStyle3: 'RSVP Estilo 3',
      rsvpStyle4: 'RSVP Estilo 4',
      rsvpStyle5: 'RSVP Estilo 5',
      rsvpStyle6: 'RSVP Estilo 6',
      rsvpStyle7: 'RSVP Estilo 7',
      bridesGrooms: 'Novias y Novios',
      serviceS2: 'Servicio S2',
      serviceS3: 'Servicio S3',
      serviceSingle: 'Servicio Single',
      plannerSingle: 'Planner Single',
      // Nuevas traducciones para el menú About
      'Cuándo y Dónde': 'Cuándo y Dónde',
      'Damas de Honor': 'Damas de Honor',
      'Guadalajara': 'Guadalajara',
      accommodation: 'Alojamiento',
      // Story section translations
      ourStory: 'Nuestra Historia',
             howItHappened: '¿CÓMO SUCEDIÓ?',
             howWeMeet: '¿Cómo nos conocimos?',
       howWeMeetDescription: '"Nuestra historia comenzó con un mensaje y se convirtió en toda una vida. En solo tres años, hemos enfrentado tanto juntos, y cada desafío solo ha hecho nuestro amor más fuerte y nuestro vínculo inquebrantable. Todo lo que hemos planeado hasta ahora ha funcionado a nuestro favor, y apreciamos convertir cada momento que compartimos en algo especial. Nos sentimos verdaderamente bendecidos de que desde el principio, ambas familias nos han amado y apoyado en cada paso del camino."',
       // Event section translations
       ourWedding: 'Nuestra Boda',
               whenAndWhere: '¿CUÁNDO Y DÓNDE?', 
       theReception: 'La Misa',
       theCeremony: 'La Ceremonia',
       theParty: 'La Fiesta',
       // Misa event
       eventDate1: 'Sábado, 18 Abr. 2026 - 5:00 PM',
       eventLocation1: 'Misa en Parroquia Santiago Apóstol (Sixto Gorjón 16, Centro, 46400 Tequila, Jal., Mexico)',
       
       eventPhone1: '+52 33-1234-5678',
       // Ceremonia event
       eventDate2: 'Sábado, 18 Abr. 2026 - Al terminar la Misa',
       eventLocation2: 'Cueva de la Luna en Tequila Jalisco ( Camino a la Toma No. 3, 46400 Tequila, Jal., Mexico)',
       eventPhone2: '+52 33-1234-5679',
       // Fiesta event
       eventDate3: 'Sábado, 18 Abr. 2026 - 8:00 PM',
       eventLocation3: 'Salón de Eventos "El Jardín"',
       eventPhone3: '+52 33-1234-5680',
       // Modal translations
       seeLocation: 'Ver Ubicación',
       // Footer translations
       links: 'Enlaces',
       about: 'Acerca de',
       services: 'Servicios',
       gallery: 'Galería',
       getQuote: 'Obtener Cotización',
       contact: 'Contacto',
       footerDescription: 'No podemos esperar a ver a todos nuestros queridos amigos y familiares en nuestra boda.',
       footerContact: 'Contacto',
       footerEmail: 'Fer & Sean@wpoceans.com',
       footerAddress: 'Tequila Jalisco, México',
       copyright: '© Copyright 2025 | Fer & Sean | Todos los derechos reservados.',
       copyrightYear: '© 2025',
       madeBy: 'Made by Kodeo',
       // About section translations
       aboutDate: '16 de Abril del 2026',
       aboutMainTitle: 'NUESTRO DÍA ESPECIAL',
       aboutDescription: 'El 16 de abril de 2026, en el mágico pueblo de Tequila, Jalisco, vamos a dar un paso muy especial en nuestras vidas y queremos celebrarlo contigo. Este día no sería el mismo sin las personas que queremos cerca, y por eso nos emociona invitarte a ser parte de esta gran fiesta de amor, alegría y buenos recuerdos.',
       aboutSignature: '- Fer & Sean',
               // Team section translations
        importantPeople: 'Personas Importantes',
                 bridesmaids: 'DAMAS DE HONOR',
        bridesmaidsEn: 'Bridesmaids',
        importantPeopleEn: 'Important People',
        // Contact page translations
        contactUs: 'Contáctanos',
        contact: 'Contacto',
        address: 'Dirección',
        addressText: 'Tequila Jalisco, México',
        emailUs: 'Envíanos un Email',
        callNow: 'Llámanos',
        haveAnyQuestion: '¿Tienes alguna pregunta?',
        contactDescription: 'Estamos aquí para ayudarte con cualquier consulta sobre nuestra boda. No dudes en contactarnos.',
        yourName: 'Tu Nombre',
        subject: 'Asunto',
        message: 'Mensaje',
        submitNow: 'Enviar',
        whatsappMessage: 'Hola, me gustaría contactarte sobre la boda de Fer & Sean.',
        // Validation messages
        requiredField: 'Este campo es requerido',
        invalidName: 'El nombre solo puede contener letras y espacios',
        photography: 'Fotografía',
        rehearsalDinner: 'Cena de Ensayo',
        afterparty: 'After Party',
        videographers: 'Videógrafos',
        perfectCake: 'Pastel Perfecto',
                allOfTheAbove: 'Todo lo Anterior',
        // Accommodation page translations
        accommodationTitle: 'Alojamiento',
        accommodationSubtitle: 'Alojamiento',
        // Guadalajara page translations
        discoverGuadalajara: 'Descubre Guadalajara',
        pearlTapatia: 'Tu Guía de la Perla Tapatía',
        welcomeGuadalajara: '¡Bienvenidos a Guadalajara!',
        guadalajaraDescription: 'La "Perla Tapatía" te espera con los brazos abiertos. Guadalajara es la segunda ciudad más grande de México y la cuna de tradiciones que han conquistado el mundo: el mariachi, el tequila y la charrería. Una ciudad que combina perfectamente la historia colonial con la modernidad, ofreciendo experiencias únicas para todos nuestros queridos invitados.',
        whySpecial: '¿Por qué es especial Guadalajara?',
        mariachiCradle: 'Cuna del Mariachi: Aquí nació la música que representa a México en el mundo',
        tequilaCapital: 'Capital del Tequila: Rodeada por los agaves que producen nuestra bebida nacional',
        culturalHeritage: 'Patrimonio Cultural: Centro histórico declarado Patrimonio de la Humanidad',
        uniqueGastronomy: 'Gastronomía única: Hogar de la torta ahogada, las carnitas y mucho más',
        placesNotToMiss: 'Lugares que No Te Puedes Perder',
        placesDescription: 'Descubre los tesoros que Guadalajara tiene para ofrecerte durante tu visita',
        historicCenter: 'Centro Histórico',
        historicCenterDesc: 'Camina por las calles empedradas, visita la majestuosa Catedral y disfruta de la Plaza de Armas. El corazón de la ciudad donde late la historia de México.',
        tlaquepaque: 'Tlaquepaque',
        tlaquepaqueDesc: 'Pueblo mágico lleno de arte, artesanías y mariachis. Perfecto para llevarte un recuerdo auténtico de México y disfrutar de la cultura local.',
        tequilaJalisco: 'Tequila, Jalisco',
        tequilaJaliscoDesc: 'A solo una hora de la ciudad, descubre los campos de agave azul y las destilerías donde nace el tequila. Una experiencia única e imperdible.',
        sanJuanMarket: 'Mercado San Juan de Dios',
        sanJuanMarketDesc: 'El mercado cubierto más grande de Latinoamérica. Aquí encontrarás desde comida tradicional hasta artesanías típicas de la región.',
        degolladoTheater: 'Teatro Degollado',
        degolladoTheaterDesc: 'Joya arquitectónica del siglo XIX donde podrás disfrutar de espectáculos de mariachi, ballet folclórico y ópera en un ambiente sublime.',
        colomosForest: 'Bosque Colomos',
        colomosForestDesc: 'Escápate del bullicio de la ciudad en este hermoso parque lleno de vegetación, lagos y espacios perfectos para relajarse y conectar con la naturaleza.',
        flavorsThatEnchant: 'Sabores que Enamoran',
        gastronomyDescription: 'La gastronomía tapatía es una experiencia que despierta todos los sentidos. Cada platillo cuenta una historia, cada sabor es una tradición que se ha pasado de generación en generación.',
        dishesToTry: 'Platillos que debes probar:',
        tortaAhogada: 'Torta Ahogada: El ícono gastronómico de Guadalajara',
        birria: 'Birria: Guiso tradicional perfecto para cualquier hora',
        carnitas: 'Carnitas: Carne de cerdo cocida en su propia grasa',
        tejuino: 'Tejuino: Bebida refrescante hecha de maíz fermentado',
        jericalla: 'Jericalla: Postre cremoso que te robará el corazón',
        // WeddingDate2 (Hotels) translations
        recommendedHotels: 'Hoteles Recomendados',
        hotelsSubtitle: 'Hemos seleccionado estos hoteles para que tengas una estancia perfecta durante nuestra celebración',
        callButton: 'Llamar',
        bookButton: 'Reservar',
        previousImage: 'Imagen anterior',
        nextImage: 'Siguiente imagen',
        goToImage: 'Ir a imagen'
       },
     en: {
      names: 'Fer & Sean',
      date: 'April 18, 2026',
      venue: '"La Cueva de la Luna"',
      location: 'Tequila Jalisco, Mexico',
      days: 'Days',
      hours: 'Hours',
      minutes: 'Min',
      seconds: 'Sec',
      comingSoonNote: 'The website with all related information will be presented soon',
      languageButton: 'ES',
      // Header translations
      home: 'Home',
      about: 'About',
      portfolio: 'Gallery',
      contact: 'Contact',
      story: 'Our Story',
      accommodation: 'Accommodation',
      rsvp: 'RSVP',
      gallery: 'Gallery',
      planners: 'Planners',
      service: 'Service',
      pricing: 'Pricing',
      authPages: 'Auth Pages',
      login: 'Login',
      register: 'Register',
      forgotPassword: 'Forgot Password',
      comingSoon: 'Coming Soon',
      error404: '404 Error',
      portfolioGrid: 'Portfolio Grid',
      portfolioMasonary: 'Portfolio Masonary',
      portfolioMasonaryS2: 'Portfolio Masonary S2',
      portfolioMasonaryS3: 'Portfolio Masonary S3',
      portfolioSingle: 'Portfolio Single',
      ourStory: 'Our Story',
      ourStoryStyle1: 'Our Story Style 1',
      ourStoryStyle2: 'Our Story Style 2',
      ourStoryStyle3: 'Our Story Style 3',
      ourStoryStyle4: 'Our Story Style 4',
      ourStoryStyle5: 'Our Story Style 5',
      ourStoryStyle6: 'Our Story Style 6',
      rsvpStyle1: 'RSVP Style 1',
      rsvpStyle2: 'RSVP Style 2',
      rsvpStyle3: 'RSVP Style 3',
      rsvpStyle4: 'RSVP Style 4',
      rsvpStyle5: 'RSVP Style 5',
      rsvpStyle6: 'RSVP Style 6',
      rsvpStyle7: 'RSVP Style 7',
      bridesGrooms: 'Brides & Grooms',
      serviceS2: 'Service S2',
      serviceS3: 'Service S3',
      serviceSingle: 'Service Single',
      plannerSingle: 'Planner Single',
      // Nuevas traducciones para el menú About
      'Cuándo y Dónde': 'When & Where',
      'Damas de Honor': 'Bridesmaids',
      'Guadalajara': 'Guadalajara',
      accommodation: 'Accommodation',
      // Story section translations
      ourStory: 'Our Story',
             howItHappened: 'HOW IT HAPPENED',
             howWeMeet: 'How we meet',
       howWeMeetDescription: '"Our story started with a message and turned into a lifetime. In just three years, we\'ve faced so much together, and every challenge has only made our love stronger and our bond unbreakable. Everything we\'ve planned so far has worked in our favor, and we cherish turning every moment we share into something special. We feel truly blessed that from the very beginning, both of our families have loved and supported us every step of the way."',
       // Event section translations
       ourWedding: 'Our Wedding',
               whenAndWhere: 'WHEN & WHERE',
       theReception: 'The Mass',
       theCeremony: 'The Ceremony',
       theParty: 'The Party',
       // Mass event
       eventDate1: 'Saturday, Apr 18, 2026 - 5:00 PM',
       eventLocation1: 'Mass at Santiago Apóstol Parish (Sixto Gorjón 16, Centro, 46400 Tequila, Jalisco, Mexico)',
       eventPhone1: '+52 33-1234-5678',
               // Ceremony event
        eventDate2: 'Saturday, Apr 18, 2026 - After Mass',
       eventLocation2: 'Cave of the Moon in Tequila, Jalisco (Camino a la Toma No. 3, 46400 Tequila, Jalisco, Mexico)',
       eventPhone2: '+52 33-1234-5679',
       // Party event
       eventDate3: 'Saturday, Apr 18, 2026 - 8:00 PM',
       eventLocation3: '"El Jardín" Event Hall',
       eventPhone3: '+52 33-1234-5680',
       // Modal translations
       seeLocation: 'See Location',
       // Footer translations
       links: 'Links',
       about: 'About',
       services: 'Services',
       gallery: 'Gallery',
       getQuote: 'Get Quote',
       contact: 'Contact',
       footerDescription: 'We can\'t wait to see all of our beloved friends and relatives at our wedding.',
       footerContact: 'Contact',
       footerEmail: 'Fer & Sean@wpoceans.com',
       footerAddress: 'Tequila Jalisco, Mexico',
       copyright: '© Copyright 2025 | Fer & Sean | All rights reserved.',
       copyrightYear: '© 2025',
       madeBy: 'Made by Kodeo',
       // About section translations
       aboutDate: 'April 16, 2026',
       aboutMainTitle: 'OUR SPECIAL DAY',
       aboutDescription: 'On April 16, 2026, in the magical town of Tequila, Jalisco, we are taking a very special step in our lives and we want to celebrate it with you. This day would not be the same without the people we want close to us, and that\'s why we are excited to invite you to be part of this great celebration of love, joy, and good memories.',
       aboutSignature: '- Fer & Sean',
               // Team section translations
        importantPeople: 'Important People',
                 bridesmaids: 'BRIDESMAIDS',
        // Contact page translations
        contactUs: 'Contact Us',
        contact: 'Contact',
        address: 'Address',
        addressText: 'Tequila Jalisco, Mexico',
        emailUs: 'Email Us',
        callNow: 'Call Now',
        haveAnyQuestion: 'Have Any Question?',
        contactDescription: 'We are here to help you with any questions about our wedding. Do not hesitate to contact us.',
        yourName: 'Your Name',
        subject: 'Subject',
        message: 'Message',
        submitNow: 'Send',
        whatsappMessage: 'Hello, I would like to contact you about Fer & Sean\'s wedding.',
        // Validation messages
        requiredField: 'This field is required',
        invalidName: 'Name can only contain letters and spaces',
        photography: 'Photography',
        rehearsalDinner: 'The Rehearsal Dinner',
        afterparty: 'The Afterparty',
        videographers: 'Videographers',
        perfectCake: 'Perfect Cake',
                allOfTheAbove: 'All Of The Above',
        // Accommodation page translations
        accommodationTitle: 'Accommodation',
        accommodationSubtitle: 'Accommodation',
        // Guadalajara page translations
        discoverGuadalajara: 'Discover Guadalajara',
        pearlTapatia: 'Your Guide to the Pearl of the West',
        welcomeGuadalajara: 'Welcome to Guadalajara!',
        guadalajaraDescription: 'The "Pearl of the West" awaits you with open arms. Guadalajara is Mexico\'s second largest city and the cradle of traditions that have conquered the world: mariachi, tequila, and charrería. A city that perfectly combines colonial history with modernity, offering unique experiences for all our dear guests.',
        whySpecial: 'Why is Guadalajara special?',
        mariachiCradle: 'Cradle of Mariachi: Here was born the music that represents Mexico to the world',
        tequilaCapital: 'Tequila Capital: Surrounded by agaves that produce our national drink',
        culturalHeritage: 'Cultural Heritage: Historic center declared a World Heritage Site',
        uniqueGastronomy: 'Unique Gastronomy: Home of the torta ahogada, carnitas, and much more',
        placesNotToMiss: 'Places You Can\'t Miss',
        placesDescription: 'Discover the treasures that Guadalajara has to offer during your visit',
        historicCenter: 'Historic Center',
        historicCenterDesc: 'Walk through the cobblestone streets, visit the majestic Cathedral and enjoy the Plaza de Armas. The heart of the city where Mexico\'s history beats.',
        tlaquepaque: 'Tlaquepaque',
        tlaquepaqueDesc: 'Magical town full of art, crafts, and mariachis. Perfect for taking home an authentic souvenir from Mexico and enjoying the local culture.',
        tequilaJalisco: 'Tequila, Jalisco',
        tequilaJaliscoDesc: 'Just an hour from the city, discover the blue agave fields and distilleries where tequila is born. A unique and unmissable experience.',
        sanJuanMarket: 'San Juan de Dios Market',
        sanJuanMarketDesc: 'The largest covered market in Latin America. Here you\'ll find everything from traditional food to typical crafts from the region.',
        degolladoTheater: 'Degollado Theater',
        degolladoTheaterDesc: '19th century architectural jewel where you can enjoy mariachi shows, folkloric ballet, and opera in a sublime atmosphere.',
        colomosForest: 'Colomos Forest',
        colomosForestDesc: 'Escape the city bustle in this beautiful park full of vegetation, lakes, and perfect spaces to relax and connect with nature.',
        flavorsThatEnchant: 'Flavors That Enchant',
        gastronomyDescription: 'Tapatía gastronomy is an experience that awakens all the senses. Each dish tells a story, each flavor is a tradition that has been passed down from generation to generation.',
        dishesToTry: 'Dishes you must try:',
        tortaAhogada: 'Torta Ahogada: The gastronomic icon of Guadalajara',
        birria: 'Birria: Traditional stew perfect for any time',
        carnitas: 'Carnitas: Pork meat cooked in its own fat',
        tejuino: 'Tejuino: Refreshing drink made from fermented corn',
        jericalla: 'Jericalla: Creamy dessert that will steal your heart',
        // WeddingDate2 (Hotels) translations
        recommendedHotels: 'Recommended Hotels',
        hotelsSubtitle: 'We have selected these hotels for you to have a perfect stay during our celebration',
        callButton: 'Call',
        bookButton: 'Book',
        previousImage: 'Previous image',
        nextImage: 'Next image',
        goToImage: 'Go to image'
       }
   };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    toggleLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}; 