import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es'); // 'es' para español, 'en' para inglés

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  };

  const translations = {
    es: {
      names: 'Fer & Sean',
      date: '18 abril 2026',
      venue: '"La Cueva de la Luna"',
      location: 'Tequila Jalisco, México',
      days: 'Días',
      hours: 'Horas',
      minutes: 'Min',
      seconds: 'Seg',
      comingSoonNote: 'Próximamente se presentará el sitio web con toda la información relacionada',
      languageButton: 'EN',
      // Header translations
      home: 'Inicio',
      about: 'Acerca de',
      portfolio: 'Galería',
      contact: 'Contacto',
      story: 'Nuestra Historia',
      accommodation: 'Alojamiento',
      rsvp: 'RSVP',
      gallery: 'Galería',
      planners: 'Planners',
      service: 'Servicio',
      pricing: 'Precios',
      authPages: 'Páginas de Auth',
      login: 'Iniciar Sesión',
      register: 'Registrarse',
      forgotPassword: 'Olvidé Contraseña',
      comingSoon: 'Próximamente',
      error404: 'Error 404',
      portfolioGrid: 'Portafolio Grid',
      portfolioMasonary: 'Portafolio Masonary',
      portfolioMasonaryS2: 'Portafolio Masonary S2',
      portfolioMasonaryS3: 'Portafolio Masonary S3',
      portfolioSingle: 'Portafolio Single',
      ourStory: 'Nuestra Historia',
      ourStoryStyle1: 'Nuestra Historia Estilo 1',
      ourStoryStyle2: 'Nuestra Historia Estilo 2',
      ourStoryStyle3: 'Nuestra Historia Estilo 3',
      ourStoryStyle4: 'Nuestra Historia Estilo 4',
      ourStoryStyle5: 'Nuestra Historia Estilo 5',
      ourStoryStyle6: 'Nuestra Historia Estilo 6',
      rsvpStyle1: 'RSVP Estilo 1',
      rsvpStyle2: 'RSVP Estilo 2',
      rsvpStyle3: 'RSVP Estilo 3',
      rsvpStyle4: 'RSVP Estilo 4',
      rsvpStyle5: 'RSVP Estilo 5',
      rsvpStyle6: 'RSVP Estilo 6',
      rsvpStyle7: 'RSVP Estilo 7',
      bridesGrooms: 'Novias y Novios',
      serviceS2: 'Servicio S2',
      serviceS3: 'Servicio S3',
      serviceSingle: 'Servicio Single',
      plannerSingle: 'Planner Single',
      // Nuevas traducciones para el menú About
      'Itinerario': 'Itinerario',
      'Dress Code': 'Código de Vestimenta',
      'Menu': 'Menú',
      'Damas de Honor': 'Damas de Honor',
      'Codigo de Vestimenta': 'Dress Code',
      'Damas y Caballeros' : 'bridesmaids and groomsmen',
      'Cercanía del punto de encuentro': 'Proximity to Meeting Point',
      accommodation: 'Alojamiento',
      // Story section translations
      ourStory: 'Nuestra Historia',
      howItHappened: '¿CÓMO SUCEDIÓ?',
      howWeMeet: '¿Cómo nos conocimos?',
      howWeMeetDescription: '"Nuestra historia comenzó con un mensaje y se convirtió en toda una vida. En solo tres años, hemos enfrentado tanto juntos, y cada desafío solo ha hecho nuestro amor más fuerte y nuestro vínculo inquebrantable. Todo lo que hemos planeado hasta ahora ha funcionado a nuestro favor, y apreciamos convertir cada momento que compartimos en algo especial. Nos sentimos verdaderamente bendecidos de que desde el principio, ambas familias nos han amado y apoyado en cada paso del camino."',
      // Event section translations
       ourWedding: 'Nuestra Boda',
       whenAndWhere: '¿Itinerario?', 
       theReception: 'La Misa',
       theCeremony: 'La Ceremonia',
       theParty: 'La Fiesta',
       // EventSection translations
       itinerary: 'Itinerario',
       itinerarySubtitle: 'Te invitamos a celebrar con nosotros en estos lugares especiales',
       Cantaritos: 'Cantaritos',
       Llegada: 'Llegada',
       // WeddingMenuSection translations
       weddingMenuTitle: 'Menú de Nuestra Boda',
       weddingMenuSubtitle: 'Hemos seleccionado cuidadosamente cada plato para hacer de este día una experiencia gastronómica memorable',
       mainMenu: 'Menú Principal',
       glutenFreeMenu: 'Menú Sin Gluten',
       glutenFreeBadge: 'Libre de Gluten',
       // Menu items
       entrada: 'Entrada',
       platoPrincipal: 'Plato Principal',
       acompanamiento: 'Acompañamiento',
       postre: 'Postre',
       // Regular menu dishes
       ensaladaCesar: 'Ensalada César con Pollo',
       ensaladaCesarDesc: 'Lechuga romana fresca, crutones caseros, queso parmesano, pechuga de pollo a la parrilla y aderezo césar tradicional.',
       salmonParrilla: 'Salmón a la Parrilla con Risotto',
       salmonParrillaDesc: 'Filete de salmón fresco a la parrilla con hierbas finas, acompañado de risotto cremoso de champiñones y espárragos.',
       verdurasMediterraneas: 'Verduras Mediterráneas',
       verdurasMediterraneasDesc: 'Mezcla de calabacín, berenjena, pimientos rojos y amarillos asados con aceite de oliva y hierbas provenzales.',
       tartaChocolate: 'Tarta de Chocolate y Frambuesas',
       tartaChocolateDesc: 'Deliciosa tarta de chocolate belga con mousse ligero, coulis de frambuesas frescas y decoración de frutas.',
       // Gluten free menu dishes
       ensaladaQuinoa: 'Ensalada de Quinoa y Aguacate',
       ensaladaQuinoaDesc: 'Quinoa orgánica, aguacate fresco, tomates cherry, pepino, cilantro y vinagreta de limón y aceite de oliva.',
       polloMediterraneo: 'Pollo Mediterráneo sin Gluten',
       polloMediterraneoDesc: 'Pechuga de pollo marinada en hierbas mediterráneas, servida con puré de coliflor y verduras grilladas.',
       arrozPilaf: 'Arroz Pilaf con Almendras',
       arrozPilafDesc: 'Arroz basmati con almendras tostadas, pasas, cebolla caramelizada y especias suaves sin gluten.',
       pannacottaVainilla: 'Pannacotta de Vainilla',
       pannacottaVainillaDesc: 'Cremoso pannacotta de vainilla natural con coulis de frutas del bosque y decoración de menta fresca.',
       // Menu note
       menuNote: 'Nota importante: Si tienes alguna alergia alimentaria o restricción dietética especial, por favor háznoslo saber al confirmar tu asistencia para que podamos preparar una alternativa adecuada.',
       // Misa event
       eventDate1: 'Sábado, 18 Abr. 2026 - 5:00 PM - 6:00 PM',
       eventLocation1: 'Misa en Parroquia Santiago Apóstol (Sixto Gorjón 16, Centro, 46400 Tequila, Jal., Mexico)',
       
       eventPhone1: '+52 33-1234-5678',
       // Ceremonia event
       llegada: 'Se remocomienda llegar el día jueves 17 de abril',
       aeropuerto: 'Aeropuerto Internacional de Guadalajara (GDL)',
       fechacantaritos: 'Viernes, 17 Abr 2026',
       lugarCantaritos: 'Carretera internacional, Carr. Guadalajara - Tepic km 49 #4970, La Meza, 45380 Amatitán, Jal.',
       eventDate2: 'Sábado, 18 Abr. 2026 - Al terminar la Misa',
       eventLocation2: 'Cueva de la Luna en Tequila Jalisco ( Camino a la Toma No. 3, 46400 Tequila, Jal., Mexico)',
       eventPhone2: '+52 33-1234-5679',
       // Fiesta event
       eventDate3: 'Sábado, 18 Abr. 2026 - 8:00 PM',
       eventLocation3: 'Salón de Eventos "El Jardín"',
       eventPhone3: '+52 33-1234-5680',
       // Modal translations
       seeLocation: 'Ver Ubicación',
       // Footer translations
       links: 'Enlaces',
       about: 'Acerca de',
       services: 'Servicios',
       gallery: 'Galería',
       getQuote: 'Obtener Cotización',
       contact: 'Contacto',
       footerDescription: 'No podemos esperar a ver a todos nuestros queridos amigos y familiares en nuestra boda.',
       footerContact: 'Contacto',
       footerEmail: 'Fer & Sean@wpoceans.com',
       footerAddress: 'Tequila Jalisco, México',
       copyright: '© Copyright 2025 | Fer & Sean | Todos los derechos reservados.',
       copyrightYear: '© 2025',
       madeBy: 'Made by Kodeo',
       // About section translations
       aboutDate: '18 de Abril del 2026',
       aboutMainTitle: 'NUESTRO DÍA ESPECIAL',
       aboutDescription: 'El 18 de abril de 2026, en el mágico pueblo de Tequila, Jalisco, vamos a dar un paso muy especial en nuestras vidas y queremos celebrarlo contigo. Este día no sería el mismo sin las personas que queremos cerca, y por eso nos emociona invitarte a ser parte de esta gran fiesta de amor, alegría y buenos recuerdos.',
       aboutSignature: '- Fer & Sean',
               // Team section translations
        importantPeople: 'Personas Importantes',
        bridesmaids: 'DAMAS DE HONOR',
        bridesmaid: 'Dama de Honor',
        groomsman: 'Caballero de Honor',
        bridesmaidsAndGroomsman: 'Damas de Honor y Caballero de Honor',
        bridesmaidsEn: 'Bridesmaids',
        importantPeopleEn: 'Important People',
        // Contact page translations
        contactUs: 'Contáctanos',
        contact: 'Contacto',
        address: 'Dirección',
        addressText: 'Tequila Jalisco, México',
        emailUs: 'Envíanos un Email',
        callNow: 'Llámanos',
        haveAnyQuestion: '¿Tienes alguna pregunta?',
        contactDescription: 'Estamos aquí para ayudarte con cualquier consulta sobre nuestra boda. No dudes en contactarnos.',
        yourName: 'Tu Nombre',
        subject: 'Asunto',
        message: 'Mensaje',
        submitNow: 'Enviar',
        whatsappMessage: 'Hola, me gustaría contactarte sobre la boda de Fer & Sean.',
        // Validation messages
        requiredField: 'Este campo es requerido',
        invalidName: 'El nombre solo puede contener letras y espacios',
        photography: 'Fotografía',
        rehearsalDinner: 'Cena de Ensayo',
        afterparty: 'After Party',
        videographers: 'Videógrafos',
        perfectCake: 'Pastel Perfecto',
                allOfTheAbove: 'Todo lo Anterior',
        // Error page translations
        oopsPageNotFound: '¡Ups! Página No Encontrada',
        errorDescription: 'Lo sentimos pero no podemos encontrar la página que solicitaste. Esto puede ser porque has escrito la dirección web incorrectamente.',
        backToHome: 'Volver al inicio',
        // Accommodation page translations
        accommodationTitle: 'Alojamiento',
        accommodationSubtitle: 'Alojamiento',
        // Guadalajara page translations
        discoverGuadalajara: 'Descubre Guadalajara',
        pearlTapatia: 'Tu Guía de la Perla Tapatía',
        welcomeGuadalajara: '¡Bienvenidos a Guadalajara!',
        guadalajaraDescription: 'La "Perla Tapatía" te espera con los brazos abiertos. Guadalajara es la segunda ciudad más grande de México y la cuna de tradiciones que han conquistado el mundo: el mariachi, el tequila y la charrería. Una ciudad que combina perfectamente la historia colonial con la modernidad, ofreciendo experiencias únicas para todos nuestros queridos invitados.',
        whySpecial: '¿Por qué es especial Guadalajara?',
        mariachiCradle: 'Cuna del Mariachi: Aquí nació la música que representa a México en el mundo',
        tequilaCapital: 'Capital del Tequila: Rodeada por los agaves que producen nuestra bebida nacional',
        culturalHeritage: 'Patrimonio Cultural: Centro histórico declarado Patrimonio de la Humanidad',
        uniqueGastronomy: 'Gastronomía única: Hogar de la torta ahogada, las carnitas y mucho más',
        placesNotToMiss: 'Lugares que No Te Puedes Perder',
        placesDescription: 'Descubre los tesoros que Guadalajara tiene para ofrecerte durante tu visita',
        historicCenter: 'Centro Histórico',
        historicCenterDesc: 'Camina por las calles empedradas, visita la majestuosa Catedral y disfruta de la Plaza de Armas. El corazón de la ciudad donde late la historia de México.',
        tlaquepaque: 'Tlaquepaque',
        tlaquepaqueDesc: 'Pueblo mágico lleno de arte, artesanías y mariachis. Perfecto para llevarte un recuerdo auténtico de México y disfrutar de la cultura local.',
        tequilaJalisco: 'Tequila, Jalisco',
        tequilaJaliscoDesc: 'A solo una hora de la ciudad, descubre los campos de agave azul y las destilerías donde nace el tequila. Una experiencia única e imperdible.',
        sanJuanMarket: 'Mercado San Juan de Dios',
        sanJuanMarketDesc: 'El mercado cubierto más grande de Latinoamérica. Aquí encontrarás desde comida tradicional hasta artesanías típicas de la región.',
        degolladoTheater: 'Teatro Degollado',
        degolladoTheaterDesc: 'Joya arquitectónica del siglo XIX donde podrás disfrutar de espectáculos de mariachi, ballet folclórico y ópera en un ambiente sublime.',
        colomosForest: 'Bosque Colomos',
        colomosForestDesc: 'Escápate del bullicio de la ciudad en este hermoso parque lleno de vegetación, lagos y espacios perfectos para relajarse y conectar con la naturaleza.',
        flavorsThatEnchant: 'Sabores que Enamoran',
        gastronomyDescription: 'La gastronomía tapatía es una experiencia que despierta todos los sentidos. Cada platillo cuenta una historia, cada sabor es una tradición que se ha pasado de generación en generación.',
        dishesToTry: 'Platillos que debes probar:',
        tortaAhogada: 'Torta Ahogada: El ícono gastronómico de Guadalajara',
        birria: 'Birria: Guiso tradicional perfecto para cualquier hora',
        carnitas: 'Carnitas: Carne de cerdo cocida en su propia grasa',
        tejuino: 'Tejuino: Bebida refrescante hecha de maíz fermentado',
        jericalla: 'Jericalla: Postre cremoso que te robará el corazón',
                 // WeddingDate2 (Hotels) translations
         recommendedHotels: 'Hoteles Recomendados',
         hotelsSubtitle: 'Hemos seleccionado estos hoteles para que tengas una estancia perfecta durante nuestra celebración',
         callButton: 'Llamar',
         bookButton: 'Reservar',
         previousImage: 'Imagen anterior',
         nextImage: 'Siguiente imagen',
         goToImage: 'Ir a imagen',
         // Hotel names and descriptions
         hotelSolarAnimas: 'Hotel Solar de las Ánimas',
         hotelSolarAnimasAddress: 'Calle Ramón Corona, 86 Colonia Centro , 46400 Jalisco, México',
         hotelSolarAnimasDescription: 'Hotel con arquitectura típica mexicana del siglo XVII. Ofrece 93 habitaciones con diseño virreinal, combinando confort moderno con historia y tradiciones de más de 490 años.',
         hotelPlazaJardin: 'Hotel Plaza Jardín',
         hotelPlazaJardinAddress: 'José Cuervo 13, La Villa, 46400 Tequila, Jal.',
         hotelPlazaJardinDescription: 'Ubicado en el centro de Tequila, este hotel ofrece un marco rústico y elegante con auténtico encanto mexicano. El lugar perfecto para construir historias inolvidables.',
         hotelNueveAgaves: 'Nueve Agaves Hotel',
         hotelNueveAgavesAddress: 'Francisco Javier Sauza Mora 21, La Villa, 46400 Tequila, Jal.',
         hotelNueveAgavesDescription: 'Hotel enfocado en brindar servicio de hospedaje cálido y confortable. Promueve la cultura y tradiciones del pueblo mágico de Tequila, garantizando una experiencia única.',
         casaTahona: 'Casa Tahona',
         casaTahonaAddress: 'C. Luis Navarro 28, Centro, 46400 Tequila, Jal.',
         casaTahonaDescription: 'Casa boutique ubicada en el centro del pueblo mágico de Tequila. A solo una cuadra de las principales atracciones, destilerías y todo lo que deseas visitar.',
         hotelCasaGranSenora: 'Hotel Casa La Gran Señora',
         hotelCasaGranSenoraAddress: 'Nicolás Bravo No. 72, Centro, 46400 Tequila, Jal.',
         hotelCasaGranSenoraDescription: 'Hotel acogedor ubicado en el centro de Tequila. Un lugar donde los huéspedes pueden descansar y disfrutar plenamente su estadía en el Paisaje Agavero.',
         hotelBarricas: 'Hotel de Barricas',
         hotelBarricasAddress: 'La Cofradía 1297 La Cofradía, 46400 Tequila, Jal.',
         hotelBarricasDescription: 'Complejo turístico único donde cada detalle está creado para una experiencia auténtica. Hospedaje especial, sabores conectados con la tierra y momentos inolvidables.',
                 // Dress Code page translations
        'Our Amazing Work': 'Nuestro Trabajo Increíble',
        // ProductSinglePage translations
        'Event Details': 'Detalles del Evento',
        'Product Single': 'Producto Individual',
        'eventDate': 'Fecha y Hora',
        'eventLocation': 'Ubicación',
        'eventDescription': 'Descripción',
        'eventDetails': 'Detalles del Evento',
        'eventLogistics': 'Logística',
        'eventMap': 'Ubicación en el Mapa',
        'contentNotFound': 'Contenido no encontrado',
        'contentNotFoundMessage': 'Lo sentimos, no pudimos encontrar la información solicitada.'
       },
     en: {
      names: 'Fer & Sean',
      date: 'April 18, 2026',
      venue: '"La Cueva de la Luna"',
      location: 'Tequila Jalisco, Mexico',
      days: 'Days',
      hours: 'Hours',
      minutes: 'Min',
      seconds: 'Sec',
      comingSoonNote: 'The website with all related information will be presented soon',
      languageButton: 'ES',
      // Header translations
      home: 'Home',
      about: 'About',
      portfolio: 'Gallery',
      contact: 'Contact',
      story: 'Our Story',
      accommodation: 'Accommodation',
      rsvp: 'RSVP',
      gallery: 'Gallery',
      planners: 'Planners',
      service: 'Service',
      pricing: 'Pricing',
      authPages: 'Auth Pages',
      login: 'Login',
      register: 'Register',
      forgotPassword: 'Forgot Password',
      comingSoon: 'Coming Soon',
      error404: '404 Error',
      portfolioGrid: 'Portfolio Grid',
      portfolioMasonary: 'Portfolio Masonary',
      portfolioMasonaryS2: 'Portfolio Masonary S2',
      portfolioMasonaryS3: 'Portfolio Masonary S3',
      portfolioSingle: 'Portfolio Single',
      ourStory: 'Our Story',
      ourStoryStyle1: 'Our Story Style 1',
      ourStoryStyle2: 'Our Story Style 2',
      ourStoryStyle3: 'Our Story Style 3',
      ourStoryStyle4: 'Our Story Style 4',
      ourStoryStyle5: 'Our Story Style 5',
      ourStoryStyle6: 'Our Story Style 6',
      rsvpStyle1: 'RSVP Style 1',
      rsvpStyle2: 'RSVP Style 2',
      rsvpStyle3: 'RSVP Style 3',
      rsvpStyle4: 'RSVP Style 4',
      rsvpStyle5: 'RSVP Style 5',
      rsvpStyle6: 'RSVP Style 6',
      rsvpStyle7: 'RSVP Style 7',
      bridesGrooms: 'Brides & Grooms',
      serviceS2: 'Service S2',
      serviceS3: 'Service S3',
      serviceSingle: 'Service Single',
      plannerSingle: 'Planner Single',
      // Nuevas traducciones para el menú About
      'Itinerario': 'When & Where',
      'Dress Code': 'Dress Code',
      'Menu': 'Menu',
      'Damas de Honor': 'Bridesmaids',
      'Guadalajara': 'Guadalajara',
      accommodation: 'Accommodation',
      // Story section translations
      ourStory: 'Our Story',
             howItHappened: 'HOW IT HAPPENED',
             howWeMeet: 'How we meet',
       howWeMeetDescription: '"Our story started with a message and turned into a lifetime. In just three years, we\'ve faced so much together, and every challenge has only made our love stronger and our bond unbreakable. Everything we\'ve planned so far has worked in our favor, and we cherish turning every moment we share into something special. We feel truly blessed that from the very beginning, both of our families have loved and supported us every step of the way."',
       // Event section translations
       ourWedding: 'Our Wedding',
       whenAndWhere: 'WHEN & WHERE',
       theReception: 'The Mass',
       theCeremony: 'The Ceremony',
       theParty: 'The Party',
       // EventSection translations
       itinerary: 'Itinerary',
       itinerarySubtitle: 'We invite you to celebrate with us in these special places',
       Cantaritos: 'Cantaritos',
       Llegada: 'Arrival',
       // WeddingMenuSection translations
       weddingMenuTitle: 'Our Wedding Menu',
       weddingMenuSubtitle: 'We have carefully selected each dish to make this day a memorable gastronomic experience',
       mainMenu: 'Main Menu',
       glutenFreeMenu: 'Gluten-Free Menu',
       glutenFreeBadge: 'Gluten Free',
       // Menu items
       entrada: 'Appetizer',
       platoPrincipal: 'Main Course',
       acompanamiento: 'Side Dish',
       postre: 'Dessert',
       // Regular menu dishes
       ensaladaCesar: 'Caesar Salad with Chicken',
       ensaladaCesarDesc: 'Fresh romaine lettuce, homemade croutons, parmesan cheese, grilled chicken breast and traditional caesar dressing.',
       salmonParrilla: 'Grilled Salmon with Risotto',
       salmonParrillaDesc: 'Fresh grilled salmon fillet with fine herbs, served with creamy mushroom and asparagus risotto.',
       verdurasMediterraneas: 'Mediterranean Vegetables',
       verdurasMediterraneasDesc: 'Mix of roasted zucchini, eggplant, red and yellow peppers with olive oil and Provençal herbs.',
       tartaChocolate: 'Chocolate and Raspberry Tart',
       tartaChocolateDesc: 'Delicious Belgian chocolate tart with light mousse, fresh raspberry coulis and fruit decoration.',
       // Gluten free menu dishes
       ensaladaQuinoa: 'Quinoa and Avocado Salad',
       ensaladaQuinoaDesc: 'Organic quinoa, fresh avocado, cherry tomatoes, cucumber, cilantro and lemon and olive oil vinaigrette.',
       polloMediterraneo: 'Mediterranean Gluten-Free Chicken',
       polloMediterraneoDesc: 'Chicken breast marinated in Mediterranean herbs, served with cauliflower puree and grilled vegetables.',
       arrozPilaf: 'Pilaf Rice with Almonds',
       arrozPilafDesc: 'Basmati rice with toasted almonds, raisins, caramelized onion and soft gluten-free spices.',
       pannacottaVainilla: 'Vanilla Pannacotta',
       pannacottaVainillaDesc: 'Creamy natural vanilla pannacotta with berry coulis and fresh mint decoration.',
       // Menu note
       menuNote: 'Important note: If you have any food allergies or special dietary restrictions, please let us know when confirming your attendance so we can prepare an appropriate alternative.',
       // Mass event
       llegada: 'We recommend arriving on Thursday, April 17',
       aeropuerto: 'Guadalajara International Airport (GDL)',
       fechacantaritos: 'Friday, April 17, 2026',
       lugarCantaritos: 'Carretera internacional, Carr. Guadalajara - Tepic km 49 #4970, La Meza, 45380 Amatitán, Jal.',
       eventDate1: 'Saturday, Apr 18, 2026 - 5:00 PM',
       eventLocation1: 'Mass at Santiago Apóstol Parish (Sixto Gorjón 16, Centro, 46400 Tequila, Jalisco, Mexico)',
       eventPhone1: '+52 33-1234-5678',
       
               // Ceremony event
        eventDate2: 'Saturday, Apr 18, 2026 - After Mass',
       eventLocation2: 'Cave of the Moon in Tequila, Jalisco (Camino a la Toma No. 3, 46400 Tequila, Jalisco, Mexico)',
       eventPhone2: '+52 33-1234-5679',
       // Party event
       eventDate3: 'Saturday, Apr 18, 2026 - 8:00 PM',
       eventLocation3: '"El Jardín" Event Hall',
       eventPhone3: '+52 33-1234-5680',
       // Modal translations
       seeLocation: 'See Location',
       // Footer translations
       links: 'Links',
       about: 'About',
       services: 'Services',
       gallery: 'Gallery',
       getQuote: 'Get Quote',
       contact: 'Contact',
       footerDescription: 'We can\'t wait to see all of our beloved friends and relatives at our wedding.',
       footerContact: 'Contact',
       footerEmail: 'Fer & Sean@wpoceans.com',
       footerAddress: 'Tequila Jalisco, Mexico',
       copyright: '© Copyright 2025 | Fer & Sean | All rights reserved.',
       copyrightYear: '© 2025',
       madeBy: 'Made by Kodeo',
       // About section translations
       aboutDate: 'April 18, 2026',
       aboutMainTitle: 'OUR SPECIAL DAY',
       aboutDescription: 'On April 18, 2026, in the magical town of Tequila, Jalisco, we are taking a very special step in our lives and we want to celebrate it with you. This day would not be the same without the people we want close to us, and that\'s why we are excited to invite you to be part of this great celebration of love, joy, and good memories.',
       aboutSignature: '- Fer & Sean',
               // Team section translations
        importantPeople: 'Important People',
        bridesmaids: 'BRIDESMAIDS',
        bridesmaid: 'Bridesmaid',
        groomsman: 'Groomsman',
        bridesmaidsAndGroomsman: 'Bridesmaids and Groomsman',
        // Contact page translations
        contactUs: 'Contact Us',
        contact: 'Contact',
        address: 'Address',
        addressText: 'Tequila Jalisco, Mexico',
        emailUs: 'Email Us',
        callNow: 'Call Now',
        haveAnyQuestion: 'Have Any Question?',
        contactDescription: 'We are here to help you with any questions about our wedding. Do not hesitate to contact us.',
        yourName: 'Your Name',
        subject: 'Subject',
        message: 'Message',
        submitNow: 'Send',
        whatsappMessage: 'Hello, I would like to contact you about Fer & Sean\'s wedding.',
        // Validation messages
        requiredField: 'This field is required',
        invalidName: 'Name can only contain letters and spaces',
        photography: 'Photography',
        rehearsalDinner: 'The Rehearsal Dinner',
        afterparty: 'The Afterparty',
        videographers: 'Videographers',
        perfectCake: 'Perfect Cake',
        allOfTheAbove: 'All Of The Above',
        // Error page translations
        oopsPageNotFound: 'Oops! Page Not Found!',
        errorDescription: 'We\'re sorry but we can\'t seem to find the page you requested. This might be because you have typed the web address incorrectly.',
        backToHome: 'Back to home',
        // Accommodation page translations
        accommodationTitle: 'Accommodation',
        accommodationSubtitle: 'Accommodation',
        // Guadalajara page translations
        discoverGuadalajara: 'Discover Guadalajara',
        pearlTapatia: 'Your Guide to the Pearl of the West',
        welcomeGuadalajara: 'Welcome to Guadalajara!',
        guadalajaraDescription: 'The "Pearl of the West" awaits you with open arms. Guadalajara is Mexico\'s second largest city and the cradle of traditions that have conquered the world: mariachi, tequila, and charrería. A city that perfectly combines colonial history with modernity, offering unique experiences for all our dear guests.',
        whySpecial: 'Why is Guadalajara special?',
        mariachiCradle: 'Cradle of Mariachi: Here was born the music that represents Mexico to the world',
        tequilaCapital: 'Tequila Capital: Surrounded by agaves that produce our national drink',
        culturalHeritage: 'Cultural Heritage: Historic center declared a World Heritage Site',
        uniqueGastronomy: 'Unique Gastronomy: Home of the torta ahogada, carnitas, and much more',
        placesNotToMiss: 'Places You Can\'t Miss',
        placesDescription: 'Discover the treasures that Guadalajara has to offer during your visit',
        historicCenter: 'Historic Center',
        historicCenterDesc: 'Walk through the cobblestone streets, visit the majestic Cathedral and enjoy the Plaza de Armas. The heart of the city where Mexico\'s history beats.',
        tlaquepaque: 'Tlaquepaque',
        tlaquepaqueDesc: 'Magical town full of art, crafts, and mariachis. Perfect for taking home an authentic souvenir from Mexico and enjoying the local culture.',
        tequilaJalisco: 'Tequila, Jalisco',
        tequilaJaliscoDesc: 'Just an hour from the city, discover the blue agave fields and distilleries where tequila is born. A unique and unmissable experience.',
        sanJuanMarket: 'San Juan de Dios Market',
        sanJuanMarketDesc: 'The largest covered market in Latin America. Here you\'ll find everything from traditional food to typical crafts from the region.',
        degolladoTheater: 'Degollado Theater',
        degolladoTheaterDesc: '19th century architectural jewel where you can enjoy mariachi shows, folkloric ballet, and opera in a sublime atmosphere.',
        colomosForest: 'Colomos Forest',
        colomosForestDesc: 'Escape the city bustle in this beautiful park full of vegetation, lakes, and perfect spaces to relax and connect with nature.',
        flavorsThatEnchant: 'Flavors That Enchant',
        gastronomyDescription: 'Tapatía gastronomy is an experience that awakens all the senses. Each dish tells a story, each flavor is a tradition that has been passed down from generation to generation.',
        dishesToTry: 'Dishes you must try:',
        tortaAhogada: 'Torta Ahogada: The gastronomic icon of Guadalajara',
        birria: 'Birria: Traditional stew perfect for any time',
        carnitas: 'Carnitas: Pork meat cooked in its own fat',
        tejuino: 'Tejuino: Refreshing drink made from fermented corn',
        jericalla: 'Jericalla: Creamy dessert that will steal your heart',
        // WeddingDate2 (Hotels) translations
        recommendedHotels: 'Recommended Hotels',
        hotelsSubtitle: 'We have selected these hotels for you to have a perfect stay during our celebration',
        callButton: 'Call',
        bookButton: 'Book',
        previousImage: 'Previous image',
        nextImage: 'Next image',
        goToImage: 'Go to image',
        // Hotel names and descriptions
        hotelSolarAnimas: 'Hotel Solar de las Ánimas',
        hotelSolarAnimasAddress: 'Calle Ramón Corona, 86 Colonia Centro , 46400 Jalisco, México',
        hotelSolarAnimasDescription: 'Hotel with typical 17th century Mexican architecture. Offers 93 rooms with viceregal design, combining modern comfort with history and traditions of more than 490 years.',
        hotelPlazaJardin: 'Hotel Plaza Jardín',
        hotelPlazaJardinAddress: 'José Cuervo 13, La Villa, 46400 Tequila, Jal.',
        hotelPlazaJardinDescription: 'Located in the center of Tequila, this hotel offers a rustic and elegant setting with authentic Mexican charm. The perfect place to build unforgettable stories.',
        hotelNueveAgaves: 'Nueve Agaves Hotel',
        hotelNueveAgavesAddress: 'Francisco Javier Sauza Mora 21, La Villa, 46400 Tequila, Jal.',
        hotelNueveAgavesDescription: 'Hotel focused on providing warm and comfortable lodging service. Promotes the culture and traditions of the magical town of Tequila, guaranteeing a unique experience.',
        casaTahona: 'Casa Tahona',
        casaTahonaAddress: 'C. Luis Navarro 28, Centro, 46400 Tequila, Jal.',
        casaTahonaDescription: 'Boutique house located in the center of the magical town of Tequila. Just one block from the main attractions, distilleries and everything you want to visit.',
        hotelCasaGranSenora: 'Hotel Casa La Gran Señora',
        hotelCasaGranSenoraAddress: 'Nicolás Bravo No. 72, Centro, 46400 Tequila, Jal.',
        hotelCasaGranSenoraDescription: 'Cozy hotel located in the center of Tequila. A place where guests can rest and fully enjoy their stay in the Agave Landscape.',
        hotelBarricas: 'Hotel de Barricas',
        hotelBarricasAddress: 'La Cofradía 1297 La Cofradía, 46400 Tequila, Jal.',
        hotelBarricasDescription: 'Unique tourist complex where every detail is created for an authentic experience. Special accommodation, flavors connected to the land and unforgettable moments.',
        // Dress Code page translations
        'Our Amazing Work': 'Our Amazing Work',
        // ProductSinglePage translations
        'Event Details': 'Event Details',
        'Product Single': 'Product Single',
        'eventDate': 'Date and Time',
        'eventLocation': 'Location',
        'eventDescription': 'Description',
        'eventDetails': 'Event Details',
        'eventLogistics': 'Logistics',
        'eventMap': 'Location on Map',
        'contentNotFound': 'Content not found',
        'contentNotFoundMessage': 'Sorry, we could not find the requested information.'
       }
   };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    toggleLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}; 